ALTER TABLE "IngestExtractedArtistRun"
  ADD COLUMN IF NOT EXISTS "errorCode" TEXT,
  ADD COLUMN IF NOT EXISTS "errorMessage" TEXT,
  ADD COLUMN IF NOT EXISTS "attemptedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS "durationMs" INTEGER;

ALTER TABLE "IngestDiscoveryJob"
  ADD COLUMN IF NOT EXISTS "durationMs" INTEGER,
  ADD COLUMN IF NOT EXISTS "candidatesQueued" INTEGER,
  ADD COLUMN IF NOT EXISTS "candidatesSkipped" INTEGER,
  ADD COLUMN IF NOT EXISTS "queryFailCount" INTEGER;
